(function (root, factory) {
  const config = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = config;
  }
  root.BRACKET_CONFIG = config;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  const GAMES = {
    FF1: { round: "ff", top: "NC State", tSeed: 11, bot: "Texas", bSeed: 11, feedsTo: "W5" },
    FF2: { round: "ff", top: "UMBC", tSeed: 16, bot: "Howard", bSeed: 16, feedsTo: "M1" },
    FF3: { round: "ff", top: "SMU", tSeed: 11, bot: "Miami (OH)", bSeed: 11, feedsTo: "M5" },
    FF4: { round: "ff", top: "Prairie View", tSeed: 16, bot: "Lehigh", bSeed: 16, feedsTo: "S1" },

    E1: { round: "r1", region: "east", top: "Duke", tSeed: 1, bot: "Siena", bSeed: 16 },
    E2: { round: "r1", region: "east", top: "Ohio St.", tSeed: 8, bot: "TCU", bSeed: 9 },
    E3: { round: "r1", region: "east", top: "St. John's", tSeed: 5, bot: "UNI", bSeed: 12 },
    E4: { round: "r1", region: "east", top: "Kansas", tSeed: 4, bot: "Cal Baptist", bSeed: 13 },
    E5: { round: "r1", region: "east", top: "Louisville", tSeed: 6, bot: "South Florida", bSeed: 11 },
    E6: { round: "r1", region: "east", top: "Michigan St.", tSeed: 3, bot: "N. Dakota St.", bSeed: 14 },
    E7: { round: "r1", region: "east", top: "UCLA", tSeed: 7, bot: "UCF", bSeed: 10 },
    E8: { round: "r1", region: "east", top: "UConn", tSeed: 2, bot: "Furman", bSeed: 15 },

    E9: { round: "r2", region: "east", src: ["E1", "E2"] },
    E10: { round: "r2", region: "east", src: ["E3", "E4"] },
    E11: { round: "r2", region: "east", src: ["E5", "E6"] },
    E12: { round: "r2", region: "east", src: ["E7", "E8"] },
    E13: { round: "s16", region: "east", src: ["E9", "E10"] },
    E14: { round: "s16", region: "east", src: ["E11", "E12"] },
    E15: { round: "e8", region: "east", src: ["E13", "E14"] },

    W1: { round: "r1", region: "west", top: "Arizona", tSeed: 1, bot: "LIU", bSeed: 16 },
    W2: { round: "r1", region: "west", top: "Villanova", tSeed: 8, bot: "Utah St.", bSeed: 9 },
    W3: { round: "r1", region: "west", top: "Wisconsin", tSeed: 5, bot: "High Point", bSeed: 12 },
    W4: { round: "r1", region: "west", top: "Arkansas", tSeed: 4, bot: "Hawaii", bSeed: 13 },
    W5: { round: "r1", region: "west", top: "BYU", tSeed: 6, bot: null, bSeed: 11, ffSrc: "FF1" },
    W6: { round: "r1", region: "west", top: "Gonzaga", tSeed: 3, bot: "Kennesaw St.", bSeed: 14 },
    W7: { round: "r1", region: "west", top: "Miami (FL)", tSeed: 7, bot: "Missouri", bSeed: 10 },
    W8: { round: "r1", region: "west", top: "Purdue", tSeed: 2, bot: "Queens", bSeed: 15 },

    W9: { round: "r2", region: "west", src: ["W1", "W2"] },
    W10: { round: "r2", region: "west", src: ["W3", "W4"] },
    W11: { round: "r2", region: "west", src: ["W5", "W6"] },
    W12: { round: "r2", region: "west", src: ["W7", "W8"] },
    W13: { round: "s16", region: "west", src: ["W9", "W10"] },
    W14: { round: "s16", region: "west", src: ["W11", "W12"] },
    W15: { round: "e8", region: "west", src: ["W13", "W14"] },

    M1: { round: "r1", region: "midwest", top: "Michigan", tSeed: 1, bot: null, bSeed: 16, ffSrc: "FF2" },
    M2: { round: "r1", region: "midwest", top: "Georgia", tSeed: 8, bot: "Saint Louis", bSeed: 9 },
    M3: { round: "r1", region: "midwest", top: "Texas Tech", tSeed: 5, bot: "Akron", bSeed: 12 },
    M4: { round: "r1", region: "midwest", top: "Alabama", tSeed: 4, bot: "Hofstra", bSeed: 13 },
    M5: { round: "r1", region: "midwest", top: "Tennessee", tSeed: 6, bot: null, bSeed: 11, ffSrc: "FF3" },
    M6: { round: "r1", region: "midwest", top: "Virginia", tSeed: 3, bot: "Wright St.", bSeed: 14 },
    M7: { round: "r1", region: "midwest", top: "Kentucky", tSeed: 7, bot: "Santa Clara", bSeed: 10 },
    M8: { round: "r1", region: "midwest", top: "Iowa St.", tSeed: 2, bot: "Tennessee St.", bSeed: 15 },

    M9: { round: "r2", region: "midwest", src: ["M1", "M2"] },
    M10: { round: "r2", region: "midwest", src: ["M3", "M4"] },
    M11: { round: "r2", region: "midwest", src: ["M5", "M6"] },
    M12: { round: "r2", region: "midwest", src: ["M7", "M8"] },
    M13: { round: "s16", region: "midwest", src: ["M9", "M10"] },
    M14: { round: "s16", region: "midwest", src: ["M11", "M12"] },
    M15: { round: "e8", region: "midwest", src: ["M13", "M14"] },

    S1: { round: "r1", region: "south", top: "Florida", tSeed: 1, bot: null, bSeed: 16, ffSrc: "FF4" },
    S2: { round: "r1", region: "south", top: "Clemson", tSeed: 8, bot: "Iowa", bSeed: 9 },
    S3: { round: "r1", region: "south", top: "Vanderbilt", tSeed: 5, bot: "McNeese", bSeed: 12 },
    S4: { round: "r1", region: "south", top: "Nebraska", tSeed: 4, bot: "Troy", bSeed: 13 },
    S5: { round: "r1", region: "south", top: "N. Carolina", tSeed: 6, bot: "VCU", bSeed: 11 },
    S6: { round: "r1", region: "south", top: "Illinois", tSeed: 3, bot: "Penn", bSeed: 14 },
    S7: { round: "r1", region: "south", top: "Saint Mary's", tSeed: 7, bot: "Texas A&M", bSeed: 10 },
    S8: { round: "r1", region: "south", top: "Houston", tSeed: 2, bot: "Idaho", bSeed: 15 },

    S9: { round: "r2", region: "south", src: ["S1", "S2"] },
    S10: { round: "r2", region: "south", src: ["S3", "S4"] },
    S11: { round: "r2", region: "south", src: ["S5", "S6"] },
    S12: { round: "r2", region: "south", src: ["S7", "S8"] },
    S13: { round: "s16", region: "south", src: ["S9", "S10"] },
    S14: { round: "s16", region: "south", src: ["S11", "S12"] },
    S15: { round: "e8", region: "south", src: ["S13", "S14"] },

    FF5: { round: "ff2", label: "East vs South", src: ["E15", "S15"] },
    FF6: { round: "ff2", label: "West vs Midwest", src: ["W15", "M15"] },
    NC: { round: "nc", label: "National Championship", src: ["FF5", "FF6"] }
  };

  const RG = {
    east: { r1: ["E1", "E2", "E3", "E4", "E5", "E6", "E7", "E8"], r2: ["E9", "E10", "E11", "E12"], s16: ["E13", "E14"], e8: ["E15"] },
    west: { r1: ["W1", "W2", "W3", "W4", "W5", "W6", "W7", "W8"], r2: ["W9", "W10", "W11", "W12"], s16: ["W13", "W14"], e8: ["W15"] },
    midwest: { r1: ["M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8"], r2: ["M9", "M10", "M11", "M12"], s16: ["M13", "M14"], e8: ["M15"] },
    south: { r1: ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8"], r2: ["S9", "S10", "S11", "S12"], s16: ["S13", "S14"], e8: ["S15"] }
  };

  const RLABELS = { ff: "First Four", r1: "Round of 64", r2: "Round of 32", s16: "Sweet 16", e8: "Elite 8", ff2: "Final Four", nc: "Championship" };
  const RPTS = { r1: 10, r2: 20, s16: 40, e8: 80, ff2: 160, nc: 320 };
  const RSHORT = { r1: "R64", r2: "R32", s16: "S16", e8: "E8", ff2: "FF", nc: "NC" };

  const LOGO_MAP = {
    Duke: "150", Siena: "399", "Ohio St.": "194", TCU: "2628", "St. John's": "2599",
    "N. Iowa": "2460", UNI: "2460", Kansas: "2305", "Cal Baptist": "2856", Louisville: "97",
    "South Florida": "58", "Michigan St.": "127", "N. Dakota St.": "2449", UCLA: "26",
    UCF: "2116", UConn: "41", Furman: "231", Arizona: "12", LIU: "288",
    Villanova: "2918", "Utah St.": "328", Wisconsin: "275", "High Point": "2314",
    Arkansas: "8", Hawaii: "62", BYU: "252", Texas: "251", Gonzaga: "2250",
    "Kennesaw St.": "2320", "Miami (FL)": "2390", Missouri: "142", Purdue: "2509",
    Queens: "2514", Michigan: "130", Howard: "47", Georgia: "61", "Saint Louis": "139",
    "Texas Tech": "2641", Akron: "2006", Alabama: "333", Hofstra: "2275",
    Tennessee: "2633", "Miami (OH)": "193", SMU: "2567", Virginia: "258",
    "Wright St.": "2750", Kentucky: "96", "Santa Clara": "2541", "Iowa St.": "66",
    "Tennessee St.": "2634", Florida: "57", "Prairie View": "2504", Lehigh: "2329",
    Clemson: "228", Iowa: "2294", Vanderbilt: "238", McNeese: "2377",
    Nebraska: "158", Troy: "2653", "N. Carolina": "153", VCU: "2670",
    Illinois: "356", Penn: "219", "Saint Mary's": "2535", "Texas A&M": "245",
    Houston: "248", Idaho: "70", "NC State": "152", UMBC: "2378"
  };

  const ESPN_TO_LOCAL = {
    "Duke Blue Devils": "Duke",
    Duke: "Duke",
    "Siena Saints": "Siena",
    Siena: "Siena",
    "Ohio State Buckeyes": "Ohio St.",
    "Ohio State": "Ohio St.",
    "TCU Horned Frogs": "TCU",
    TCU: "TCU",
    "St. John's Red Storm": "St. John's",
    "St. John's (NY) Red Storm": "St. John's",
    "St. John's": "St. John's",
    "Northern Iowa Panthers": "UNI",
    "Northern Iowa": "UNI",
    "UNI Panthers": "UNI",
    UNI: "UNI",
    "N. Iowa": "UNI",
    "Kansas Jayhawks": "Kansas",
    Kansas: "Kansas",
    "California Baptist Lancers": "Cal Baptist",
    "Cal Baptist": "Cal Baptist",
    "Louisville Cardinals": "Louisville",
    Louisville: "Louisville",
    "South Florida Bulls": "South Florida",
    "South Florida": "South Florida",
    "USF Bulls": "South Florida",
    "Michigan State Spartans": "Michigan St.",
    "Michigan State": "Michigan St.",
    "Michigan St": "Michigan St.",
    "North Dakota State Bison": "N. Dakota St.",
    "North Dakota State": "N. Dakota St.",
    "North Dakota St": "N. Dakota St.",
    "NDSU Bison": "N. Dakota St.",
    "UCLA Bruins": "UCLA",
    UCLA: "UCLA",
    "UCF Knights": "UCF",
    UCF: "UCF",
    "UConn Huskies": "UConn",
    "Connecticut Huskies": "UConn",
    UConn: "UConn",
    Connecticut: "UConn",
    "Furman Paladins": "Furman",
    Furman: "Furman",
    "Arizona Wildcats": "Arizona",
    Arizona: "Arizona",
    "LIU Sharks": "LIU",
    "Long Island University Sharks": "LIU",
    LIU: "LIU",
    "Villanova Wildcats": "Villanova",
    Villanova: "Villanova",
    "Utah State Aggies": "Utah St.",
    "Utah State": "Utah St.",
    "Utah St": "Utah St.",
    "Wisconsin Badgers": "Wisconsin",
    Wisconsin: "Wisconsin",
    "High Point Panthers": "High Point",
    "High Point": "High Point",
    "Arkansas Razorbacks": "Arkansas",
    Arkansas: "Arkansas",
    "Hawai'i Rainbow Warriors": "Hawaii",
    "Hawaii Rainbow Warriors": "Hawaii",
    Hawaii: "Hawaii",
    "BYU Cougars": "BYU",
    BYU: "BYU",
    "Gonzaga Bulldogs": "Gonzaga",
    Gonzaga: "Gonzaga",
    "Kennesaw State Owls": "Kennesaw St.",
    "Kennesaw State": "Kennesaw St.",
    "Kennesaw St": "Kennesaw St.",
    "Miami Hurricanes": "Miami (FL)",
    Miami: "Miami (FL)",
    "Missouri Tigers": "Missouri",
    Missouri: "Missouri",
    "Purdue Boilermakers": "Purdue",
    Purdue: "Purdue",
    "Queens Royals": "Queens",
    "Queens University Royals": "Queens",
    "Queens (NC)": "Queens",
    Queens: "Queens",
    "Michigan Wolverines": "Michigan",
    Michigan: "Michigan",
    "Georgia Bulldogs": "Georgia",
    Georgia: "Georgia",
    "Saint Louis Billikens": "Saint Louis",
    "Saint Louis": "Saint Louis",
    "Texas Tech Red Raiders": "Texas Tech",
    "Texas Tech": "Texas Tech",
    "Akron Zips": "Akron",
    Akron: "Akron",
    "Alabama Crimson Tide": "Alabama",
    Alabama: "Alabama",
    "Hofstra Pride": "Hofstra",
    Hofstra: "Hofstra",
    "Tennessee Volunteers": "Tennessee",
    Tennessee: "Tennessee",
    "Virginia Cavaliers": "Virginia",
    Virginia: "Virginia",
    "Wright State Raiders": "Wright St.",
    "Wright State": "Wright St.",
    "Wright St": "Wright St.",
    Kentucky: "Kentucky",
    "Kentucky Wildcats": "Kentucky",
    "Santa Clara Broncos": "Santa Clara",
    "Santa Clara": "Santa Clara",
    "Iowa State Cyclones": "Iowa St.",
    "Iowa State": "Iowa St.",
    "Iowa St": "Iowa St.",
    "Tennessee State Tigers": "Tennessee St.",
    "Tennessee State": "Tennessee St.",
    "Tennessee St": "Tennessee St.",
    "Florida Gators": "Florida",
    Florida: "Florida",
    "Clemson Tigers": "Clemson",
    Clemson: "Clemson",
    "Iowa Hawkeyes": "Iowa",
    Iowa: "Iowa",
    "Vanderbilt Commodores": "Vanderbilt",
    Vanderbilt: "Vanderbilt",
    "McNeese Cowboys": "McNeese",
    "McNeese State Cowboys": "McNeese",
    McNeese: "McNeese",
    "Nebraska Cornhuskers": "Nebraska",
    Nebraska: "Nebraska",
    "Troy Trojans": "Troy",
    Troy: "Troy",
    "North Carolina Tar Heels": "N. Carolina",
    "North Carolina": "N. Carolina",
    "UNC Tar Heels": "N. Carolina",
    "VCU Rams": "VCU",
    VCU: "VCU",
    "Illinois Fighting Illini": "Illinois",
    Illinois: "Illinois",
    "Penn Quakers": "Penn",
    "Pennsylvania Quakers": "Penn",
    Penn: "Penn",
    "Saint Mary's Gaels": "Saint Mary's",
    "Saint Mary's": "Saint Mary's",
    "Saint Mary's (CA)": "Saint Mary's",
    "Texas A&M Aggies": "Texas A&M",
    "Texas A&M": "Texas A&M",
    "Houston Cougars": "Houston",
    Houston: "Houston",
    "Idaho Vandals": "Idaho",
    Idaho: "Idaho",
    "NC State Wolfpack": "NC State",
    "NC State": "NC State",
    "Texas Longhorns": "Texas",
    Texas: "Texas",
    "UMBC Retrievers": "UMBC",
    UMBC: "UMBC",
    "Howard Bison": "Howard",
    Howard: "Howard",
    "SMU Mustangs": "SMU",
    SMU: "SMU",
    "Miami (OH) RedHawks": "Miami (OH)",
    "Miami (Ohio)": "Miami (OH)",
    "Miami (OH)": "Miami (OH)",
    "Prairie View A&M Panthers": "Prairie View",
    "Prairie View A&M": "Prairie View",
    "Prairie View": "Prairie View",
    "Lehigh Mountain Hawks": "Lehigh",
    Lehigh: "Lehigh"
  };

  return {
    ESPN_TO_LOCAL,
    GAMES,
    LOGO_MAP,
    RG,
    RLABELS,
    RPTS,
    RSHORT
  };
});
